language: java
jdk: openjdk19

services:
  - docker

install:

before_script:

script:
  - mvn test
  - docker build -t cloud-helloworld .
  - docker tag cloud-helloworld maloef/cloud-helloworld:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push maloef/cloud-helloworld:latest
